# Generated by Django 4.2.7 on 2023-11-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
