# Generated by Django 4.2.7 on 2023-12-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0004_alter_collection_card_alter_collection_trainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(default='Default Collection Description'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name',
            field=models.CharField(default='Your Default Value', max_length=255),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_date',
            field=models.DateTimeField(null=True),  # Allow null temporarily
        ),
    ]