# Generated by Django 4.2.7 on 2023-12-12 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0005_collection_description_collection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
